# import os
# import sys
# from io import BytesIO
# from pathlib import Path
# from dotenv import load_dotenv
# load_dotenv()

# sys.path.insert(0, str(Path(__file__).parent))
# from google_drive_service import get_google_drive_service, upload_to_google_drive

# def test_google_drive_connection():
#     print("Testing Google Drive connection...")
#     service = get_google_drive_service()
#     if not service:
#         print("Google Drive service not available. Check configuration.")
#         return False
    
#     if not service.is_authenticated():
#         print("Google Drive service not authenticated. Check credentials.")
#         return False
    
#     print("Google Drive service is authenticated and ready.")
#     return True

# def test_google_drive_upload():
#     """Test uploading a sample file to Google Drive."""
#     print("\nTesting Google Drive upload...")
    
#     # Create a sample file content
#     sample_content = "This is a test file for Google Drive integration.\nGenerated by stock data application."
#     file_buffer = BytesIO(sample_content.encode('utf-8'))
    
#     # Test upload
#     success = upload_to_google_drive(
#         file_buffer=file_buffer,
#         filename="test_google_drive_integration.txt",
#         data_type="general"
#     )
    
#     if success:
#         print("✅ Test file uploaded successfully to Google Drive.")
#         return True
#     else:
#         print("❌ Failed to upload test file to Google Drive.")
#         return False

# def main():
#     """Run Google Drive integration tests."""
#     print("Google Drive Integration Test")
#     print("=" * 40)
    
#     # Check if Google Drive is enabled
#     google_drive_enabled = os.getenv('GOOGLE_DRIVE_ENABLED', 'false').lower() in ('true', '1', 'yes')
#     if not google_drive_enabled:
#         print("❌ Google Drive integration is disabled.")
#         print("Set GOOGLE_DRIVE_ENABLED=true in your environment to enable it.")
#         return
    
#     # Test connection
#     if not test_google_drive_connection():
#         return
    
#     # Test upload
#     if test_google_drive_upload():
#         print("\n🎉 Google Drive integration is working correctly!")
#     else:
#         print("\n❌ Google Drive integration test failed.")

# if __name__ == "__main__":
#     main()
